### ISSUE TITLE
check to see if barplot() can be dropped from the chapter 2 examples.

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/SDM4inR#20]

**Comment by nicholasjhorton** [comment]
Proposal: drop barplot() and add equivalent of 
barchart(yield ~ variety, group=site, stack=TRUE, auto.key=TRUE, data=barley)
to reproduce figure 2.10 on page 26.

Same is needed for IS4 in R I suspect.

**Comment by deveaux69** [comment]
Ok, but yield is quantitative, so I’m not sure what this bar chart shows.

And is there an easy way to make them not counts but column proportions so that the heights match ? :)

(Also, what’s wrong with barplot?)

I actually much prefer mosaic plots, although not necessarily the implementation in R.
