### ISSUE TITLE
CIsim() note

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/SDM4inR#22]
On Oct 21, 2016, at 9:43 AM, Shu-Min Liao sliao@amherst.edu wrote:

Dear Nick,

One more thing: The CIsim() example in "SDM4 in R”, Chapter 18, page 2, should definitely be changed. It’s NOT on proportions, and the negative values on the “estimate” (y-axis) would really confuse some students…….

Hope this helps,
Shu-Min

**Comment by nicholasjhorton** [comment]
@sarahmcdonald20 can you please review this?  Thanks in advance, Nick

**Comment by sarahmcdonald20** [comment]
Hi @nicholasjhorton ,

I'm having trouble understanding what is meant by "proportions". I've been trying to figure it out with Bonnie and Margaret but to not much avail. Would she like the y-axis label and scale changed? CIsim() has default scales. 

Thanks,
Sarah

**Comment by nicholasjhorton** [comment]
Sarah,

Let's loop in Prof. Liao who made the original request (https://github.com/nicholasjhorton/SDM4inR/issues/22#issuecomment-396944338).

Shu-Min,

Is this issue addressed?  If not, can you please elaborate?

Thanks in advance,

Nick


> On Jun 13, 2018, at 9:50 AM, sarahmcdonald20 <notifications@github.com> wrote:
> 
> Hi @nicholasjhorton ,
> 
> I'm having trouble understanding what is meant by "proportions". I've been trying to figure it out with Bonnie and Margaret but to not much avail. Would she like the y-axis label and scale changed? CIsim() has default scales.
> 
> Thanks,
> Sarah
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000

**Comment by nicholasjhorton** [comment]
Fixed via https://github.com/nicholasjhorton/SDM4inR/commit/3e4f8ae7344e579ec5b88cf0e667d681bc2245b3

**Comment by LiaoGitHub** [comment]
Dear Nick and Sarah, 
 
Wow, I frankly didn't remember this issue which I asked about two years ago..... 

After checking ?CIsim() and spending some time digging into my mailbox, I think the issue was about the *original* example which didn't result in CIs for "proportions"; the default setting for CIsim() is for t.test/means, and that's why you would see *negative* values on the y-axis (as it was testing for the null hypothesis that the population *mean*, \mu, is equal to zero) when running the original example: 

set.seed(1988)
CIsim(n = 100, samples = 20)

This example should definitely be changed, if the purpose is to demonstrates CIs for "proportions".  

Hope this helps, 
Shu-Min

**Comment by nicholasjhorton** [comment]
Shu-Min,

I’ve posted the revision. Can you please confirm it’s now correct?

Thanks in advance, 

Nick
