### ISSUE TITLE
update front page of SDM4 in R website

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/SDM4inR#27]
The front page is a bit stark at present (see https://nhorton.people.amherst.edu/sdm4/).  @sarahmcdonald20 can you please work to add some additional material about these materials, the mosaic project, and a pointer to the book website at Pearson?

**Comment by sarahmcdonald20** [comment]
Hi Nick,

I've made some changes to the front page and wanted to preview them on the website. What was the code to update the changes into the _site folder? Thanks! @nicholasjhorton

**Comment by nicholasjhorton** [comment]
See https://rmarkdown.rstudio.com/rmarkdown_websites.html

You'll probably want to spend some time reviewing the documentation and seeing some of the bells and whistles that are supported.

It might sense to include a theme.  Suggestions welcomed.

**Comment by sarahmcdonald20** [comment]
Hi Nick,

I've been trying to play around with it. I was thinking a picture of the textbook that when clicked on, leads to the chapter sections, making navigation easier. However, I am not sure about copyrighted images so that is just an idea. I've also hyperlinked some words because I found the web addresses to be slightly overwhelming when reading (if that's alright). As for the theme, I am not quite sure what you mean: as in color scheme of the website or general layout?

Thanks!

**Comment by nicholasjhorton** [comment]
Can you and Margaret prototype a few options?  It’s fine to include a screenshot of the book cover. 

All the best,

Nick

**Comment by nicholasjhorton** [comment]
Any updates on this front?  Are we ready to publish?

**Comment by sarahmcdonald20** [comment]
I am working on updating the 'other resources' tab but should be done after that. Will let you know!

**Comment by nicholasjhorton** [comment]
Done via https://github.com/nicholasjhorton/SDM4inR/commit/2c5e6395fc931b67fd360bb2d4499dc43e605042 

Last change for comments by @deveaux69 @pvelleman or @patrick714
